---

name: Mirror to GitHub

on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: calvinbui/gitea-actions:localhost

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 📋 Mirror to GitHub
        run: ./mirror-to-github.sh
        env:
          USER_NAME: ${{ github.actor }}
          GH_PAT: ${{ secrets.GH_PAT }}
          REPOSITORY: ${{ github.repository }}

      - name: 🔊 Notification
        uses: ravsamhq/notify-slack-action@v2
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          notification_title: "{emoji} *<{run_url}|{workflow}>* {status_message} in <{repo_url}|{repo}> on <{commit_url}|{commit_sha}>"
          message_format: ""
          footer: ""
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
