---

kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master

steps:
  - name: mirror-to-github
    image: calvinbui/alpine-tools:localhost
    environment:
      GITHUB_PAT:
        from_secret: github_pat
    commands:
      - ./.drone/mirror-to-github.sh
