---

name: Gatsby

on:
  push:
    branches:
      - master

concurrency:
  group: gatsby
  cancel-in-progress: true

env:
  TZ: "Australia/Sydney"

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Check out master branch
        uses: actions/checkout@v6
        with:
          ref: master

      - name: 💭 Get nvm version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: ⚙️ Setup node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: 🧶 Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: 🧶 Restore Yarn cache
        id: cache-yarn-restore
        uses: actions/cache/restore@v5
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 🧶 Yarn install
        run: yarn install --immutable

      - name: 💨 ESLint
        run: yarn lint:js

      - name: ☄️ markdownlint
        run: yarn lint:md

      - name: 🥡 Restore Gatsby cache
        uses: actions/cache/restore@v5
        id: cache-gatsby-restore
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('gatsby-config.mjs', 'gatsby-node.js', 'gatsby-browser.js', 'gatsby-ssr.js', 'package.json', '**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: 🧶 Yarn build
        run: yarn build

      - name: ⤴️ Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: public

      - name: 🧶 Save Yarn cache
        uses: actions/cache/save@v5
        if: always() && steps.cache-yarn-restore.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ steps.cache-yarn-restore.outputs.cache-primary-key }}

      - name: 🥡 Save Gatsby cache
        uses: actions/cache/save@v5
        if: always() && steps.cache-gatsby-restore.outputs.cache-hit != 'true'
        with:
          path: |
            public
            .cache
          key: ${{ steps.cache-gatsby-restore.outputs.cache-primary-key }}

  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    needs: build-and-lint

    steps:
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
